NUMPY

In [1]:
import numpy as np

list1 = [1,2,3,4,5,6,7,8,9]
array1 = np.array(list1)

print(array1)

[1 2 3 4 5 6 7 8 9]


In [2]:
array2D = np.array([[1,2,3],[4,5,6]])
print(array2D)

[[1 2 3]
 [4 5 6]]


In [3]:
array3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
print(array1.shape)
print(array2D.shape)
print(array3D.shape)

(9,)
(2, 3)
(2, 2, 3)


In [5]:
annualSalesAndImprovements = np.array([[10000,20000,30000,40000],[0,100,100,100],[5000,15000,25000,35000]])
print(annualSalesAndImprovements)
annualSalesAndImprovements.size
annualSalesAndImprovements.dtype

[[10000 20000 30000 40000]
 [    0   100   100   100]
 [ 5000 15000 25000 35000]]


dtype('int32')

In [6]:
annualSalesAndImprovements.ndim

2

In [7]:
sales = np.zeros((5,))
print(sales)

[0. 0. 0. 0. 0.]


In [8]:
sales[2] = 10
print(sales)
print(sales[-1])

[ 0.  0. 10.  0.  0.]
0.0


In [9]:
sales2 = np.ones((5,))
print(sales2)

[1. 1. 1. 1. 1.]


In [10]:
np.arange(1,10,3)

array([1, 4, 7])

In [11]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [12]:
np.random.rand(4,4)
np.random.randint(1,100,(4,4))

array([[56, 58, 16, 74],
       [33, 18, 48, 60],
       [32, 66, 39, 65],
       [12, 51, 63,  1]])

In [13]:
print(array2D)
array2D[1,2]

[[1 2 3]
 [4 5 6]]


6

In [14]:
array10 = np.array([10,20,30,40,50,60,70,80,90,100])
print(array10[2:5])
print(array10[:5])
print(array10[::2])

[30 40 50]
[10 20 30 40 50]
[10 30 50 70 90]


In [15]:
array11 = np.array([10,20,30,40,50,60,70,80,90,100])
array12 = np.array([100,200,300,400,500,600,700,800,900,1000])
print(array11+array12)
print(array11*array12)
print(array11-array12)
print(array11/array12)
sqrtOfArray11 =  np.sqrt(array11)

[ 110  220  330  440  550  660  770  880  990 1100]
[  1000   4000   9000  16000  25000  36000  49000  64000  81000 100000]
[ -90 -180 -270 -360 -450 -540 -630 -720 -810 -900]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


NUMPY IN REAL LIFE

In [16]:
import numpy as np

prices = np.array([10,20,30,40,50])
saledQuantities = np.array([18,20,35,44,15])

totalSalesForEach = prices * saledQuantities
print(totalSalesForEach)

[ 180  400 1050 1760  750]


In [17]:
#totalSales = totalSalesForEach.sum()
totalSales = np.sum(totalSalesForEach)
print(totalSales)

4140


In [ ]:
unitsInStock = np.array([100,200,300,400,500])
prices = np.array([10,20,30,40,50])
saledQuantities = np.array([18,20,35,44,15])

newStock = unitsInStock - saledQuantities
print(newStock) 

[ 82 180 265 356 485]


In [19]:
critical = newStock < 100
print(critical)

[ True False False False False]
